require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_requirements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SystemRequirement. As you add validations to SystemRequirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemRequirement.create! valid_attributes
      get system_requirements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_requirement = SystemRequirement.create! valid_attributes
      get system_requirement_url(system_requirement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_requirement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      system_requirement = SystemRequirement.create! valid_attributes
      get edit_system_requirement_url(system_requirement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemRequirement" do
        expect {
          post system_requirements_url, params: { system_requirement: valid_attributes }
        }.to change(SystemRequirement, :count).by(1)
      end

      it "redirects to the created system_requirement" do
        post system_requirements_url, params: { system_requirement: valid_attributes }
        expect(response).to redirect_to(system_requirement_url(SystemRequirement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemRequirement" do
        expect {
          post system_requirements_url, params: { system_requirement: invalid_attributes }
        }.to change(SystemRequirement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post system_requirements_url, params: { system_requirement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        patch system_requirement_url(system_requirement), params: { system_requirement: new_attributes }
        system_requirement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        patch system_requirement_url(system_requirement), params: { system_requirement: new_attributes }
        system_requirement.reload
        expect(response).to redirect_to(system_requirement_url(system_requirement))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        system_requirement = SystemRequirement.create! valid_attributes
        patch system_requirement_url(system_requirement), params: { system_requirement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_requirement" do
      system_requirement = SystemRequirement.create! valid_attributes
      expect {
        delete system_requirement_url(system_requirement)
      }.to change(SystemRequirement, :count).by(-1)
    end

    it "redirects to the system_requirements list" do
      system_requirement = SystemRequirement.create! valid_attributes
      delete system_requirement_url(system_requirement)
      expect(response).to redirect_to(system_requirements_url)
    end
  end
end
